# Default configuration
# Copy this template to config.yaml and edit as appropriate

stream:
    port: COM6
    baudrate: 9600

file:
    log: tsg.log
    data: tsg.csv

database:
    db: tsg.db
    #db: C:/Users/CSL 2/Documents/LOCNESS_data/locness.db
    table: tsg